basic_settings:
  site_title: Jules connects dots
  favicon_image: /images/favicon.png
header_settings:
  logo_image:
  logo_width: 100
menu_settings:
  menu_items:
    - title: Additional Work
      url: www.vault.julesconnectsdots.com
    - title: Schedule a chat
      url: https://cal.com/jules-monza/intro-convo
footer_settings:
  logo_image:
  logo_width: 100
  tagline: built with Jekyll + Cloudcannon + Github
hero_settings:
  background_image: /images/backgrounds/background-hero.svg
post_settings:
  grid_spacing: 10
contact_settings:
  email_address: jules.r.monza@hey.com
  form_action: https://formspree.io/hello@jekyllthemes.io
  confirmation_url: /thanks
  email_subject: Connecting our dots
  send_button_text: Get in touch
social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: https://github.com/jpswizzle/
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: https://open.spotify.com/user/juropel
  bandcamp_url: ''
  linkedin_url: https://www.linkedin.com/in/julesmonza/
color_settings:
  background_color: '#ffffff'
  background_alt_color: '#eaeaf5'
  text_dark_color: '#04035e'
  text_medium_color: '#2321ad'
  text_light_color: '#a8a7c7'
  accent_color: '#5648d2'
  border_color: '#e2e1f0'
  error_color: '#e63a28'
  purple_swizzle_500: '#5648D2'
  purple_swizzle_700: '#2321AD'
  purple_swizzle_800: '#100E94'
  purple_swizzle_900: '#05047A'
  purple_swizzle_950: '#04035E'
  greytint_purple_100: '#EAEAF5'
  greytint_purple_200: '#E2E1F0'
  greytint_purple_300: '#D3D3E5'
  greytint_purple_400: '#BDBCD6'
  greytint_purple_500: '#A8A7C7'
  greytint_purple_600: '#9494B8'
  greytint_purple_700: '#8382AB'
font_settings:
  font_embed: >-
    <link
    href="https://fonts.googleapis.com/css?family=Rubik:400,500,700|Source+Sans+3:wght@300,400,700&display=swap"
    rel="stylesheet">
  title_font: Rubik, sans-serif
  body_font: '"Source Sans 3", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 700
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 64
    line_height_small: 44
  h2:
    size: 48
    size_small: 36
    weight: 500
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 48
    line_height_small: 36
  h3:
    size: 40
    size_small: 30
    weight: 500
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 42
    line_height_small: 30
  h4:
    size: 32
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 30
    line_height_small: 30
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.4
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.4
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 20
    medium_size: 28
    large_size: 32
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4
advanced_settings:
  ajax_loading: true
  analytics_code: ''
  custom_styles: ''
  header_js: ''
  footer_js: ''
